# Generated by Django 5.2.5 on 2025-08-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cause', models.CharField(choices=[('Education for All', 'Education for All'), ('Green Plantation', 'Green Plantation'), ('Slum Development', 'Slum Development'), ('General Fund', 'General Fund')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI Payment'), ('Card', 'Credit/Debit Card'), ('Bank', 'Bank Transfer')], max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
